// GERADO por _gen.py — não editar à mão; alterar o mapa de conceitos no gerador.
export type Kind = "text" | "num" | "date" | "badge" | "money" | "estado" | "notas";
export type SourceId = "geral" | "mp" | "bo" | "caixa" | "est" | "stripe" | "viva";

export interface Source { id: SourceId; label: string; color: string; }
export const SOURCES: Source[] = [
  { id: "geral", label: "Reserva", color: "#4f8cff" },
  { id: "mp", label: "Multipark", color: "#4f8cff" },
  { id: "bo", label: "Backoffice", color: "#7c5cff" },
  { id: "caixa", label: "Caixa", color: "#2ecc71" },
  { id: "est", label: "Estatística", color: "#1abc9c" },
  { id: "stripe", label: "Stripe (online)", color: "#635bff" },
  { id: "viva", label: "Viva (TPA)", color: "#ffb454" },
];

export interface ColDef { key: string; label: string; source: SourceId; kind: Kind; defaultOn?: boolean; }

export const COLUMNS: ColDef[] = [
  { key: "revisao_estado", label: "Revisão", source: "geral", kind: "estado", defaultOn: true },
  { key: "tem_notas", label: "Notas", source: "geral", kind: "notas", defaultOn: true },
  { key: "multipark_id", label: "ID Multipark", source: "geral", kind: "text", defaultOn: true },
  { key: "cidade", label: "Cidade", source: "geral", kind: "badge", defaultOn: true },
  { key: "estado_reserva", label: "Estado", source: "geral", kind: "badge", defaultOn: true },
  { key: "parque", label: "Parque", source: "geral", kind: "text" },
  { key: "n_diferencas", label: "Nº difs", source: "geral", kind: "num", defaultOn: true },
  { key: "campos_diferentes", label: "Campos diferentes", source: "geral", kind: "text", defaultOn: true },
  { key: "situacao_campanha", label: "Situação campanha", source: "geral", kind: "badge", defaultOn: true },
  { key: "matricula_mp", label: "Matrícula", source: "mp", kind: "text", defaultOn: true, },
  { key: "email_mp", label: "Email", source: "mp", kind: "text", },
  { key: "cliente_mp", label: "Cliente", source: "mp", kind: "text", },
  { key: "pi_mp", label: "PaymentIntent", source: "mp", kind: "text", },
  { key: "entrada_mp", label: "Entrada", source: "mp", kind: "date", },
  { key: "saida_mp", label: "Saída", source: "mp", kind: "date", defaultOn: true, },
  { key: "valor_mp", label: "Valor reserva", source: "mp", kind: "money", defaultOn: true, },
  { key: "preco_original_mp", label: "Preço original", source: "mp", kind: "money", },
  { key: "valet_mp", label: "Valet (entrega)", source: "mp", kind: "money", },
  { key: "metodo_mp", label: "Método", source: "mp", kind: "badge", defaultOn: true, },
  { key: "campanha_mp", label: "Campanha", source: "mp", kind: "badge", defaultOn: true, },
  { key: "matricula_bo", label: "Matrícula", source: "bo", kind: "text", defaultOn: true, },
  { key: "email_bo", label: "Email", source: "bo", kind: "text", },
  { key: "telefone_bo", label: "Telefone", source: "bo", kind: "text", },
  { key: "cliente_bo", label: "Cliente", source: "bo", kind: "text", },
  { key: "pi_bo", label: "PaymentIntent", source: "bo", kind: "text", },
  { key: "entrada_bo", label: "Entrada", source: "bo", kind: "date", },
  { key: "saida_bo", label: "Saída", source: "bo", kind: "date", defaultOn: true, },
  { key: "bookingdate_bo", label: "Data reserva", source: "bo", kind: "date", },
  { key: "valor_bo", label: "Valor reserva", source: "bo", kind: "money", defaultOn: true, },
  { key: "price_on_delivery_bo", label: "A pagar na entrega", source: "bo", kind: "money", },
  { key: "valet_bo", label: "Valet (entrega)", source: "bo", kind: "money", },
  { key: "preco_corrigido_bo", label: "Preço corrigido", source: "bo", kind: "money", },
  { key: "correcao_bo", label: "Correção", source: "bo", kind: "money", },
  { key: "metodo_bo", label: "Método", source: "bo", kind: "badge", defaultOn: true, },
  { key: "hasonline_bo", label: "Tem pgto online", source: "bo", kind: "badge", },
  { key: "campanha_bo", label: "Campanha", source: "bo", kind: "badge", defaultOn: true, },
  { key: "campaignpay_bo", label: "CampaignPay", source: "bo", kind: "badge", },
  { key: "action_bo", label: "Action final", source: "bo", kind: "badge", defaultOn: true, },
  { key: "actiondate_bo", label: "Data action", source: "bo", kind: "date", },
  { key: "actionuser_bo", label: "Util. action", source: "bo", kind: "badge", },
  { key: "validated_bo", label: "Validado", source: "bo", kind: "badge", },
  { key: "validatedby_bo", label: "Validado por", source: "bo", kind: "badge", },
  { key: "validateddate_bo", label: "Data validação", source: "bo", kind: "date", },
  { key: "drivervalidated_bo", label: "Motorista validado", source: "bo", kind: "badge", },
  { key: "drivervalidatedby_bo", label: "Motorista val. por", source: "bo", kind: "badge", },
  { key: "drivervalidateddate_bo", label: "Motorista val. data", source: "bo", kind: "date", },
  { key: "closedbooking_bo", label: "Reserva fechada", source: "bo", kind: "badge", },
  { key: "closedby_bo", label: "Fechado por", source: "bo", kind: "badge", },
  { key: "closeddate_bo", label: "Data fecho", source: "bo", kind: "date", },
  { key: "condutorrecolha_bo", label: "Condutor recolha", source: "bo", kind: "badge", },
  { key: "condutorentrega_bo", label: "Condutor entrega", source: "bo", kind: "badge", },
  { key: "condutormov_bo", label: "Condutor mov.", source: "bo", kind: "badge", },
  { key: "ocorrence_bo", label: "Ocorrência", source: "bo", kind: "badge", },
  { key: "ocorrencetype_bo", label: "Tipo ocorrência", source: "bo", kind: "badge", },
  { key: "ocorrenceremarks_bo", label: "Obs ocorrência", source: "bo", kind: "text", },
  { key: "bookingremarks_bo", label: "Obs reserva", source: "bo", kind: "text", },
  { key: "remarks_bo", label: "Observações", source: "bo", kind: "text", },
  { key: "credit_bo", label: "Crédito", source: "bo", kind: "badge", },
  { key: "pricings_bo", label: "Pricings", source: "bo", kind: "text", },
  { key: "idclient_bo", label: "ID cliente", source: "bo", kind: "text", },
  { key: "dif_valor_bo", label: "Δ Valor", source: "bo", kind: "money" },
  { key: "matricula_caixa", label: "Matrícula", source: "caixa", kind: "text", defaultOn: true, },
  { key: "email_caixa", label: "Email", source: "caixa", kind: "text", },
  { key: "pi_caixa", label: "PaymentIntent", source: "caixa", kind: "text", },
  { key: "entrada_caixa", label: "Entrada", source: "caixa", kind: "date", },
  { key: "saida_caixa", label: "Saída", source: "caixa", kind: "date", defaultOn: true, },
  { key: "bookingdate_caixa", label: "Data reserva", source: "caixa", kind: "date", },
  { key: "valor_caixa", label: "Valor reserva", source: "caixa", kind: "money", defaultOn: true, },
  { key: "price_on_delivery_caixa", label: "A pagar na entrega", source: "caixa", kind: "money", },
  { key: "preco_corrigido_caixa", label: "Preço corrigido", source: "caixa", kind: "money", },
  { key: "correcao_caixa", label: "Correção", source: "caixa", kind: "money", },
  { key: "pago_caixa", label: "Valor pago", source: "caixa", kind: "money", defaultOn: true, },
  { key: "por_pagar_caixa", label: "Por pagar/receber", source: "caixa", kind: "money", },
  { key: "metodo_caixa", label: "Método", source: "caixa", kind: "badge", defaultOn: true, },
  { key: "hasonline_caixa", label: "Tem pgto online", source: "caixa", kind: "badge", },
  { key: "campanha_caixa", label: "Campanha", source: "caixa", kind: "badge", defaultOn: true, },
  { key: "campaignpay_caixa", label: "CampaignPay", source: "caixa", kind: "badge", },
  { key: "action_caixa", label: "Action final", source: "caixa", kind: "badge", defaultOn: true, },
  { key: "actiondate_caixa", label: "Data action", source: "caixa", kind: "date", },
  { key: "actionuser_caixa", label: "Util. action", source: "caixa", kind: "badge", },
  { key: "validated_caixa", label: "Validado", source: "caixa", kind: "badge", },
  { key: "validatedby_caixa", label: "Validado por", source: "caixa", kind: "badge", },
  { key: "validateddate_caixa", label: "Data validação", source: "caixa", kind: "date", },
  { key: "drivervalidated_caixa", label: "Motorista validado", source: "caixa", kind: "badge", },
  { key: "drivervalidatedby_caixa", label: "Motorista val. por", source: "caixa", kind: "badge", },
  { key: "drivervalidateddate_caixa", label: "Motorista val. data", source: "caixa", kind: "date", },
  { key: "closedbooking_caixa", label: "Reserva fechada", source: "caixa", kind: "badge", },
  { key: "closedby_caixa", label: "Fechado por", source: "caixa", kind: "badge", },
  { key: "closeddate_caixa", label: "Data fecho", source: "caixa", kind: "date", },
  { key: "condutorrecolha_caixa", label: "Condutor recolha", source: "caixa", kind: "badge", },
  { key: "condutorentrega_caixa", label: "Condutor entrega", source: "caixa", kind: "badge", },
  { key: "condutormov_caixa", label: "Condutor mov.", source: "caixa", kind: "badge", },
  { key: "ocorrence_caixa", label: "Ocorrência", source: "caixa", kind: "badge", },
  { key: "ocorrencetype_caixa", label: "Tipo ocorrência", source: "caixa", kind: "badge", },
  { key: "ocorrenceremarks_caixa", label: "Obs ocorrência", source: "caixa", kind: "text", },
  { key: "bookingremarks_caixa", label: "Obs reserva", source: "caixa", kind: "text", },
  { key: "remarks_caixa", label: "Observações", source: "caixa", kind: "text", },
  { key: "credit_caixa", label: "Crédito", source: "caixa", kind: "badge", },
  { key: "pricings_caixa", label: "Pricings", source: "caixa", kind: "text", },
  { key: "idclient_caixa", label: "ID cliente", source: "caixa", kind: "text", },
  { key: "dif_valor_caixa", label: "Δ Valor", source: "caixa", kind: "money" },
  { key: "n_caixa", label: "# mov.", source: "caixa", kind: "num" },
  { key: "matricula_est", label: "Matrícula", source: "est", kind: "text", defaultOn: true, },
  { key: "cliente_est", label: "Cliente", source: "est", kind: "text", },
  { key: "saida_est", label: "Saída", source: "est", kind: "date", defaultOn: true, },
  { key: "valor_est", label: "Valor reserva", source: "est", kind: "money", defaultOn: true, },
  { key: "preco_original_est", label: "Preço original", source: "est", kind: "money", },
  { key: "pago_est", label: "Valor pago", source: "est", kind: "money", defaultOn: true, },
  { key: "por_pagar_est", label: "Por pagar/receber", source: "est", kind: "money", },
  { key: "metodo_est", label: "Método", source: "est", kind: "badge", defaultOn: true, },
  { key: "email_stripe", label: "Email", source: "stripe", kind: "text", },
  { key: "telefone_stripe", label: "Telefone", source: "stripe", kind: "text", },
  { key: "cliente_stripe", label: "Cliente", source: "stripe", kind: "text", },
  { key: "pi_stripe", label: "PaymentIntent", source: "stripe", kind: "text", },
  { key: "pago_stripe", label: "Valor pago", source: "stripe", kind: "money", defaultOn: true, },
  { key: "statuspgto_stripe", label: "Estado pagamento", source: "stripe", kind: "badge", },
  { key: "tipo_stripe", label: "Tipo", source: "stripe", kind: "badge" },
  { key: "reembolso_stripe", label: "Reembolso", source: "stripe", kind: "money" },
  { key: "dif_pago_stripe", label: "Δ Pago", source: "stripe", kind: "money" },
  { key: "email_viva", label: "Email", source: "viva", kind: "text", },
  { key: "telefone_viva", label: "Telefone", source: "viva", kind: "text", },
  { key: "pago_viva", label: "Valor pago", source: "viva", kind: "money", defaultOn: true, },
  { key: "statuspgto_viva", label: "Estado pagamento", source: "viva", kind: "badge", },
  { key: "tipo_viva", label: "Cartão", source: "viva", kind: "badge" },
];

export const FLAGS: { key: string; label: string; on?: boolean }[] = [
  { key: "matricula_bate", label: "Matrícula bate", },
  { key: "email_bate", label: "Email bate", },
  { key: "telefone_bate", label: "Telefone bate", },
  { key: "cliente_bate", label: "Cliente bate", },
  { key: "pi_bate", label: "PaymentIntent bate", },
  { key: "entrada_bate", label: "Entrada bate", },
  { key: "saida_bate", label: "Saída bate", on: true, },
  { key: "bookingdate_bate", label: "Data reserva bate", },
  { key: "valor_bate", label: "Valor reserva bate", on: true, },
  { key: "preco_original_bate", label: "Preço original bate", },
  { key: "price_on_delivery_bate", label: "A pagar na entrega bate", },
  { key: "valet_bate", label: "Valet (entrega) bate", },
  { key: "preco_corrigido_bate", label: "Preço corrigido bate", },
  { key: "correcao_bate", label: "Correção bate", },
  { key: "pago_bate", label: "Valor pago bate", },
  { key: "por_pagar_bate", label: "Por pagar/receber bate", },
  { key: "metodo_bate", label: "Método bate", on: true, },
  { key: "hasonline_bate", label: "Tem pgto online bate", },
  { key: "campanha_bate", label: "Campanha bate", on: true, },
  { key: "campaignpay_bate", label: "CampaignPay bate", },
  { key: "action_bate", label: "Action final bate", on: true, },
  { key: "actiondate_bate", label: "Data action bate", },
  { key: "actionuser_bate", label: "Util. action bate", },
  { key: "validated_bate", label: "Validado bate", },
  { key: "validatedby_bate", label: "Validado por bate", },
  { key: "validateddate_bate", label: "Data validação bate", },
  { key: "drivervalidated_bate", label: "Motorista validado bate", },
  { key: "drivervalidatedby_bate", label: "Motorista val. por bate", },
  { key: "drivervalidateddate_bate", label: "Motorista val. data bate", },
  { key: "closedbooking_bate", label: "Reserva fechada bate", },
  { key: "closedby_bate", label: "Fechado por bate", },
  { key: "closeddate_bate", label: "Data fecho bate", },
  { key: "condutorrecolha_bate", label: "Condutor recolha bate", },
  { key: "condutorentrega_bate", label: "Condutor entrega bate", },
  { key: "condutormov_bate", label: "Condutor mov. bate", },
  { key: "ocorrence_bate", label: "Ocorrência bate", },
  { key: "ocorrencetype_bate", label: "Tipo ocorrência bate", },
  { key: "ocorrenceremarks_bate", label: "Obs ocorrência bate", },
  { key: "bookingremarks_bate", label: "Obs reserva bate", },
  { key: "remarks_bate", label: "Observações bate", },
  { key: "credit_bate", label: "Crédito bate", },
  { key: "pricings_bate", label: "Pricings bate", },
  { key: "idclient_bate", label: "ID cliente bate", },
  { key: "statuspgto_bate", label: "Estado pagamento bate", },
  { key: "campanha_ok", label: "Campanha c/ pgto", on: true },
  { key: "tem_stripe", label: "Tem Stripe" },
];

export type Row = Record<string, unknown> & {
  multipark_id: string;
  n_diferencas: number | null;
};

export const RAW_KEYS = ["raw_mp", "raw_bo", "raw_caixa", "raw_stripe", "raw_est", "raw_viva"] as const;

export interface Filters {
  search?: string;
  cidade?: string;
  estado?: string;
  metodo?: string;
  tipoStripe?: string;
  soDivergencias?: boolean;
  comPi?: "" | "sim" | "nao";
  dataDe?: string;
  dataAte?: string;
  soFechoCaixa?: boolean;
  metodoDiverge?: boolean;
  campanhaDiverge?: boolean;
  actionDiverge?: boolean;
  campanhaSemPgto?: boolean;
  soComDiferencas?: boolean;
  revisaoEstado?: string;
  revisto?: string;
  acaoOcorrencia?: boolean;
}
